name: flutter_notebook
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.5
  flutter_native_splash: ^2.2.15
  riverpod: ^2.2.0
  rxdart: ^0.27.7
  flutter_riverpod: ^2.3.0
  uuid: ^3.0.7
  dio: ^5.0.1
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  flutter_launcher_icons: "^0.11.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
